language: php
php:
  - 5.6

install:
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer self-update
  - composer update

before_script:
  - psql -c 'create database music_xml_analyzer;' -U postgres
  - php artisan migrate

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v

sudo: false

branches:
  only:
    - staging
    - deploy

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

deploy:
  provider: heroku
  api_key: ba42860f-c45d-4c88-8f7e-f7df15b88444
  app:
    staging: music-xml-analyzer-staging
    deploy: music-xml-analyzer
  run:
    - "php artisan migrate"
