language: php

php:
  - 5.6.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e "create database IF NOT EXISTS test;" -uroot

sudo: false

services: mysql

script: vendor/bin/phpunit