language: php

php:
  - 5.6

before_script:
  - mysql -e "drop database IF EXISTS music_xml_analyzer;" -uroot
  - mysql -e "create database IF NOT EXISTS music_xml_analyzer;" -uroot
  - php artisan migrate

install:
  - composer self-update
  - composer update

sudo: false

services: mysql

script: vendor/bin/phpunit