language: php

php:
  - 5.6

before_script:
  - mysql -e "drop database IF EXISTS music_xml_analyzer;" -uroot
  - mysql -e "create database IF NOT EXISTS music_xml_analyzer;" -uroot
  - php artisan migrate

install:
  - composer self-update
  - composer update

sudo: false

branches:
  only:
    - deploy

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

deploy:
  provider: heroku
  api_key: ba42860f-c45d-4c88-8f7e-f7df15b88444
  app: music-xml-analyzer
  on: deploy
  run:
    - "pg:reset d2htlpsclvbnqt"
    - "php artisan migrate"

services: mysql

script: vendor/bin/phpunit