language: php

php:
  - 5.6

before_script:
  - mysql -e "drop database IF EXISTS music_xml_analyzer;" -uroot
  - mysql -e "create database IF NOT EXISTS music_xml_analyzer;" -uroot
  - php artisan migrate

install:
  - composer update --prefer-source

sudo: false

branches:
  only:
    - staging

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

deploy:
  provider: heroku
  api_key: ba42860f-c45d-4c88-8f7e-f7df15b88444
  app: music-xml-analyzer-staging
  on: staging
  run:
    - "php artisan migrate"
    - "php artisan migrate:refresh"

services: mysql

script: vendor/bin/phpunit