language: php

php:
  - 5.6

before_script:
  - mysql -e "create database IF NOT EXISTS music_xml_analyzer;" -uroot

install:
  - composer install --prefer-source --no-interaction --dev
  - composer self-update
  - composer update

sudo: false

services: mysql

script: vendor/bin/phpunit